baseurl: /horizons
permalink: /:collection/:year/:month/:day/:title/
collections:
  sevilla:
    output: true
prose:
  rooturl: '_sevilla'
  siteurl: 'http://katie7r.github.io/horizons/'
  relativeLinks: 'http://katie7r.github.io/horizons/links.jsonp'
  media: 'media'
  metadata:
    _sevilla:
      - name: "category"
        field:
          element: "hidden"
          value: "adventure"
      - name: "layout"
        field:
          element: "hidden"
          value: "adventure"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
            - name: "Pears"
              value: "pears"
            - name: "Mangos"
              value: "mangos"
    _sevilla/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "adventure"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
